AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Lambda sending emails

Parameters:
  CognitoAuthorizerArn:
    Type: 'AWS::SSM::Parameter::Value<String>'
    Description: Reference to Cognito UserPool for the stage
    Default: CognitoAuthorizerArn
  CustomDomain:
    Type: 'AWS::SSM::Parameter::Value<String>'
    Description: The default domain that is used as from_address
    Default: CustomDomain
  CustomDomainBasePath:
    Type: String
    Description: Base path mapping in CustomDomain
    Default: email
  ApiDomain:
    Type: 'AWS::SSM::Parameter::Value<String>'
    Description: The Api domain
    Default: /NVA/ApiDomain

Globals:
  Function:
    Timeout: 900
    MemorySize: 1798
    Runtime: java11

Resources:
  LmsCanvasServiceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: [ lambda.amazonaws.com ]
            Action: [ 'sts:AssumeRole' ]
      Policies:
        - PolicyName: writeLog
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: !Sub 'arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:*:*'

  LmsCanvasGatewayAPI:
    Type: AWS::Serverless::Api
    Properties:
      StageName: v1
      EndpointConfiguration:
        Type: REGIONAL
      MethodSettings:
        - ResourcePath: /lms
          HttpMethod: GET
      DefinitionBody:
        'Fn::Transform':
          Name: AWS::Include
          Parameters:
            Location: ./docs/openapi.yaml

  LmsCanvasLaunchFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lms-canvas
      Handler: no.sikt.nva.lms.CanvasLaunchHandler::handleRequest
      Role: !GetAtt LmsCanvasServiceRole.Arn
      Runtime: java11
      MemorySize: 1798
      Events:
        Type: Api
          Properties:
            Path: /lms
            Method: get
            RestApiId: !Ref LmsCanvasGatewayApi
      Environment:
        Variables:
          ALLOWED_ORIGIN: '*'
        PutEvent:

  LmsCanvasBasePathMapping:
    Type: AWS::ApiGateway::BasePathMapping
    Properties:
      BasePath: !Sub ${CustomDomainBasePath}
      DomainName: !Ref ApiDomain
      RestApiId: !Ref LmsCanvasGatewayApi
      Stage: !Ref LmsCanvasGatewayApi.Stage
