openapi: 3.0.0
info:
  version: '1.0'
  title: DLR LaunchCanvas API
  license:
    name: MIT
paths:
  /lms/lti/canvas/{serviceId}:
    get:
      parameters:
        - name: serviceId
          in: path
          required: true
          schema:
            type: string
      summary: Launch DLR in canvas
      operationId: ltiLaunch
      tags:
        - canvas
      x-amazon-apigateway-integration:
        uri:
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${LmsCanvasLaunchFunction.Arn}/invocations
        httpMethod: GET
        type: AWS_PROXY
      responses:
        '200':
          description: Request has succeeded, HTML or XML in response, depending on service identifier requested
          content:
            application/xml:
              schema:
                $ref: '#/components/schemas/Cartridge'
            text/html:
              schema:
                $ref: '#/components/schemas/HTML'
        '304':
          description: Redirect succeeded

        '500':
          description: Unexpected error
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: Bad lti launch request, unknown consumer key
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:
    Error:
      type: object
      required:
        - detail
        - title
        - status
      properties:
        detail:
          type: string
        message:
          type: string
        status:
          type: integer
          format: int32
    Cartridge:
      type: object
      xml:
        name: cartridge_basiclti_link
    HTML:
      type: object






