openapi: 3.0.0
info:
  version: '1.0'
  title: 'lms'
  license:
    name: MIT
paths:
  /lms/lti/canvas/{serviceId}:
    parameters:
      - in: path
        name: serviceId
        schema:
          type: string
        required: true

    get:
      summary: ''
      operationId: ltiLaunch
      tags:
        - canvas
      x-amazon-apigateway-integration:
        uri:
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${LmsCanvasLaunchFunction.Arn}/invocations
        httpMethod: GET
        type: AWS_PROXY
      responses:
        '200':
          description: ''
          content:
            application/xml:
              schema:
                $ref: '#/components/schemas/Cartridge'
            text/html:
              schema:
                $ref: '#/components/schemas/HTML'
        '304':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Json'
        '500':
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: Bad lti launch request
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:
    Error:
      type: object
      required:
        - code
        - message
    Cartridge:
      type: object
      xml:
        name: cartridge_basiclti_link
    HTML:
      type: object
    Json:
      type: object





